
nodes:
  hosts:
    # nfha-1 will be the initial primary redis master
    nfha-1:
      ansible_host: 192.168.103.248
      ansible_user: sdhags
    nfha-2:
      ansible_host: 192.168.103.150
      ansible_user: stevedh
    nfha-3:
      ansible_host: 192.168.103.217
      ansible_user: stevedh


    
