#      ___           ___   
#     /__/\         /  /\  
#     \  \:\       /  /:/_ 
#      \  \:\     /  /:/ /\
#  _____\__\:\   /  /:/ /:/
# /__/::::::::\ /__/:/ /:/ 
# \  \:\~~\~~\/ \  \:\/:/  
#  \  \:\  ~~~   \  \::/   
#   \  \:\        \  \:\   
#    \  \:\        \  \:\  
#     \__\/         \__\/
#     
#

# Welcome to the NF example docker-compose.  This file should stand up
# a functioning NF instance on your desktop.  Before running
# you should just check a few things:
#  1. several containers need a writable volume, which this file puts in /tmp by default
#  2. if the BACnet service fails to start, you may need to specify
#   which interface to use in its environment.
#
# This compose file runs attached to the local network in host network
# mode.  This is required for BACnet/IP broadcast traffic to work correctly
# on the local network


version: "2.2"
services:

  # the main container which runs all the NF services, load balancer,
  # and management console.
  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:3.1
    network_mode: host
    depends_on:
      - redis
    tmpfs:
      - /run:exec
      - /etc/nginx/conf.d/
      - /tmp
    environment:
      - APPLICATION_PATH=/http-8080/localhost
      - CONSOLE_USERNAME=admin
      - CONSOLE_PASSWORD=pw
      
#  if you want data to be persistent, you need to mount /var in the container
#  a volume
#    volumes:
#      - /tmp/nf:/var

  # Most persistent data is in redis.  This is essentially an
  #  unmodified upstream with RediSearch and RedisTimeseries installed.
  redis:
    ports:
      - "6379:6379"
    image: normalframework.azurecr.io/normalframework/redis:3.1
    volumes:
      - /tmp/nf-redis:/data

  
