version: "2"

volumes:
  redis-db:
  nf-var:

services:
  redis:
    image: normalframework.azurecr.io/normalframework/redis:3092714d
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "redis-db:/data"

  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:3092714d
    network_mode: host
    privileged: true
    environment:
      - PORT=80
    depends_on:
      - redis
    volumes:
      - "nf-var:/var/nf"

