# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from normalgw.platform import logs_pb2 as normalgw_dot_platform_dot_logs__pb2


class LogsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLogs = channel.unary_stream(
                '/normalgw.platform.Logs/GetLogs',
                request_serializer=normalgw_dot_platform_dot_logs__pb2.GetLogRequest.SerializeToString,
                response_deserializer=normalgw_dot_platform_dot_logs__pb2.LogMessage.FromString,
                )


class LogsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLogs,
                    request_deserializer=normalgw_dot_platform_dot_logs__pb2.GetLogRequest.FromString,
                    response_serializer=normalgw_dot_platform_dot_logs__pb2.LogMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'normalgw.platform.Logs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Logs(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/normalgw.platform.Logs/GetLogs',
            normalgw_dot_platform_dot_logs__pb2.GetLogRequest.SerializeToString,
            normalgw_dot_platform_dot_logs__pb2.LogMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
