#      ___           ___   
#     /__/\         /  /\  
#     \  \:\       /  /:/_ 
#      \  \:\     /  /:/ /\
#  _____\__\:\   /  /:/ /:/
# /__/::::::::\ /__/:/ /:/ 
# \  \:\~~\~~\/ \  \:\/:/  
#  \  \:\  ~~~   \  \::/   
#   \  \:\        \  \:\   
#    \  \:\        \  \:\  
#     \__\/         \__\/
#     
#

# Welcome to the NF example docker-compose.  This file should stand up
# a functioning NF instance on your desktop.  Before running
# you should just check a few things:
#  1. several containers need a writable volume, otherwise data does not persist
#  2. if the BACnet service fails to start, you may need to specify
#   which interface to use in its environment.
#
# This file runs in host networking mode to allow you to discovery
# BACnet devices on your local network.
#
# This will only work on Linux; host networking is not supported in Docker for Mac.

version: "2.2"
services:

  # the main container which runs all the NF services, load balancer,
  # and management console.
  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:1.4
    network_mode: host
    depends_on:
      - redis
#  if you want data to be persistent, you need to mount /var in the container
#  a volume
    volumes:
      - /tmp/nf:/var/nf
    env_file: auth.sh

  # Most persistent data is in redis.  This is essentially an
  #  unmodified upstream with RediSearch and RedisTimeseries installed.
  redis:
    image: normalframework.azurecr.io/normalframework/redis:1.5
    ports:
      - "6379:6379"

#  /data in redis must be set to a persistent volume
    volumes:
      - /tmp/nf-redis:/data
