// source: normalgw/hpl/management.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.normalgw.bacnet.GetHplStatusReply', null, global);
goog.exportSymbol('proto.normalgw.bacnet.GetHplStatusRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.bacnet.GetHplStatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.normalgw.bacnet.GetHplStatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.bacnet.GetHplStatusRequest.displayName = 'proto.normalgw.bacnet.GetHplStatusRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.bacnet.GetHplStatusReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.normalgw.bacnet.GetHplStatusReply.repeatedFields_, null);
};
goog.inherits(proto.normalgw.bacnet.GetHplStatusReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.bacnet.GetHplStatusReply.displayName = 'proto.normalgw.bacnet.GetHplStatusReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.bacnet.GetHplStatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.bacnet.GetHplStatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.bacnet.GetHplStatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.bacnet.GetHplStatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.bacnet.GetHplStatusRequest}
 */
proto.normalgw.bacnet.GetHplStatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.bacnet.GetHplStatusRequest;
  return proto.normalgw.bacnet.GetHplStatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.bacnet.GetHplStatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.bacnet.GetHplStatusRequest}
 */
proto.normalgw.bacnet.GetHplStatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.bacnet.GetHplStatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.bacnet.GetHplStatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.bacnet.GetHplStatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.bacnet.GetHplStatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.normalgw.bacnet.GetHplStatusReply.repeatedFields_ = [7,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.bacnet.GetHplStatusReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.bacnet.GetHplStatusReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.bacnet.GetHplStatusReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    friendlyName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pointsAvailable: jspb.Message.getFieldWithDefault(msg, 3, 0),
    pointsEnabled: jspb.Message.getFieldWithDefault(msg, 4, 0),
    statusAttrsMap: (f = msg.getStatusAttrsMap()) ? f.toObject(includeInstance, undefined) : [],
    success5mStart: (f = msg.getSuccess5mStart()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    success5mList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    errors5mStart: (f = msg.getErrors5mStart()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    errors5mList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply}
 */
proto.normalgw.bacnet.GetHplStatusReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.bacnet.GetHplStatusReply;
  return proto.normalgw.bacnet.GetHplStatusReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.bacnet.GetHplStatusReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply}
 */
proto.normalgw.bacnet.GetHplStatusReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFriendlyName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPointsAvailable(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPointsEnabled(value);
      break;
    case 5:
      var value = msg.getStatusAttrsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setSuccess5mStart(value);
      break;
    case 7:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setSuccess5mList(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setErrors5mStart(value);
      break;
    case 9:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setErrors5mList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.bacnet.GetHplStatusReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.bacnet.GetHplStatusReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.bacnet.GetHplStatusReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFriendlyName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPointsAvailable();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getPointsEnabled();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getStatusAttrsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getSuccess5mStart();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getSuccess5mList();
  if (f.length > 0) {
    writer.writePackedInt32(
      7,
      f
    );
  }
  f = message.getErrors5mStart();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getErrors5mList();
  if (f.length > 0) {
    writer.writePackedInt32(
      9,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string friendly_name = 2;
 * @return {string}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getFriendlyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setFriendlyName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 points_available = 3;
 * @return {number}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getPointsAvailable = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setPointsAvailable = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 points_enabled = 4;
 * @return {number}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getPointsEnabled = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setPointsEnabled = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * map<string, string> status_attrs = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getStatusAttrsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.clearStatusAttrsMap = function() {
  this.getStatusAttrsMap().clear();
  return this;};


/**
 * optional google.protobuf.Timestamp success_5m_start = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getSuccess5mStart = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
*/
proto.normalgw.bacnet.GetHplStatusReply.prototype.setSuccess5mStart = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.clearSuccess5mStart = function() {
  return this.setSuccess5mStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.hasSuccess5mStart = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated int32 success_5m = 7;
 * @return {!Array<number>}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getSuccess5mList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setSuccess5mList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.addSuccess5m = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.clearSuccess5mList = function() {
  return this.setSuccess5mList([]);
};


/**
 * optional google.protobuf.Timestamp errors_5m_start = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getErrors5mStart = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
*/
proto.normalgw.bacnet.GetHplStatusReply.prototype.setErrors5mStart = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.clearErrors5mStart = function() {
  return this.setErrors5mStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.hasErrors5mStart = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated int32 errors_5m = 9;
 * @return {!Array<number>}
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.getErrors5mList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.setErrors5mList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.addErrors5m = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.bacnet.GetHplStatusReply} returns this
 */
proto.normalgw.bacnet.GetHplStatusReply.prototype.clearErrors5mList = function() {
  return this.setErrors5mList([]);
};


goog.object.extend(exports, proto.normalgw.bacnet);
