// source: normalgw/platform/config.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.normalgw.platform.GetSystemInformationReply', null, global);
goog.exportSymbol('proto.normalgw.platform.GetSystemInformationRequest', null, global);
goog.exportSymbol('proto.normalgw.platform.NetworkInterfaceDetails', null, global);
goog.exportSymbol('proto.normalgw.platform.NetworkInterfaceList', null, global);
goog.exportSymbol('proto.normalgw.platform.ServiceStatus', null, global);
goog.exportSymbol('proto.normalgw.platform.ServiceStatusDetails', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.platform.NetworkInterfaceList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.normalgw.platform.NetworkInterfaceList.repeatedFields_, null);
};
goog.inherits(proto.normalgw.platform.NetworkInterfaceList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.platform.NetworkInterfaceList.displayName = 'proto.normalgw.platform.NetworkInterfaceList';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.platform.NetworkInterfaceDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.normalgw.platform.NetworkInterfaceDetails.repeatedFields_, null);
};
goog.inherits(proto.normalgw.platform.NetworkInterfaceDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.platform.NetworkInterfaceDetails.displayName = 'proto.normalgw.platform.NetworkInterfaceDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.platform.ServiceStatusDetails = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.normalgw.platform.ServiceStatusDetails.repeatedFields_, null);
};
goog.inherits(proto.normalgw.platform.ServiceStatusDetails, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.platform.ServiceStatusDetails.displayName = 'proto.normalgw.platform.ServiceStatusDetails';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.platform.GetSystemInformationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.normalgw.platform.GetSystemInformationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.platform.GetSystemInformationRequest.displayName = 'proto.normalgw.platform.GetSystemInformationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.normalgw.platform.GetSystemInformationReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.normalgw.platform.GetSystemInformationReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.normalgw.platform.GetSystemInformationReply.displayName = 'proto.normalgw.platform.GetSystemInformationReply';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.normalgw.platform.NetworkInterfaceList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.platform.NetworkInterfaceList.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.platform.NetworkInterfaceList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.platform.NetworkInterfaceList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.NetworkInterfaceList.toObject = function(includeInstance, msg) {
  var f, obj = {
    interfacesList: jspb.Message.toObjectList(msg.getInterfacesList(),
    proto.normalgw.platform.NetworkInterfaceDetails.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.platform.NetworkInterfaceList}
 */
proto.normalgw.platform.NetworkInterfaceList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.platform.NetworkInterfaceList;
  return proto.normalgw.platform.NetworkInterfaceList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.platform.NetworkInterfaceList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.platform.NetworkInterfaceList}
 */
proto.normalgw.platform.NetworkInterfaceList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.normalgw.platform.NetworkInterfaceDetails;
      reader.readMessage(value,proto.normalgw.platform.NetworkInterfaceDetails.deserializeBinaryFromReader);
      msg.addInterfaces(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.platform.NetworkInterfaceList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.platform.NetworkInterfaceList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.platform.NetworkInterfaceList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.NetworkInterfaceList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInterfacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.normalgw.platform.NetworkInterfaceDetails.serializeBinaryToWriter
    );
  }
};


/**
 * repeated NetworkInterfaceDetails interfaces = 1;
 * @return {!Array<!proto.normalgw.platform.NetworkInterfaceDetails>}
 */
proto.normalgw.platform.NetworkInterfaceList.prototype.getInterfacesList = function() {
  return /** @type{!Array<!proto.normalgw.platform.NetworkInterfaceDetails>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.normalgw.platform.NetworkInterfaceDetails, 1));
};


/**
 * @param {!Array<!proto.normalgw.platform.NetworkInterfaceDetails>} value
 * @return {!proto.normalgw.platform.NetworkInterfaceList} returns this
*/
proto.normalgw.platform.NetworkInterfaceList.prototype.setInterfacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.normalgw.platform.NetworkInterfaceDetails=} opt_value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails}
 */
proto.normalgw.platform.NetworkInterfaceList.prototype.addInterfaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.normalgw.platform.NetworkInterfaceDetails, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.NetworkInterfaceList} returns this
 */
proto.normalgw.platform.NetworkInterfaceList.prototype.clearInterfacesList = function() {
  return this.setInterfacesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.normalgw.platform.NetworkInterfaceDetails.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.platform.NetworkInterfaceDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.platform.NetworkInterfaceDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.NetworkInterfaceDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    attrId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    interfaceName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ipv4Addr: msg.getIpv4Addr_asB64(),
    mask: jspb.Message.getFieldWithDefault(msg, 4, 0),
    ipv4DefaultRoute: msg.getIpv4DefaultRoute_asB64(),
    ipv4DnsList: msg.getIpv4DnsList_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails}
 */
proto.normalgw.platform.NetworkInterfaceDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.platform.NetworkInterfaceDetails;
  return proto.normalgw.platform.NetworkInterfaceDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.platform.NetworkInterfaceDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails}
 */
proto.normalgw.platform.NetworkInterfaceDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAttrId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInterfaceName(value);
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setIpv4Addr(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMask(value);
      break;
    case 5:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setIpv4DefaultRoute(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.addIpv4Dns(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.platform.NetworkInterfaceDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.platform.NetworkInterfaceDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.NetworkInterfaceDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAttrId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getInterfaceName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIpv4Addr_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = message.getMask();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getIpv4DefaultRoute_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      5,
      f
    );
  }
  f = message.getIpv4DnsList_asU8();
  if (f.length > 0) {
    writer.writeRepeatedBytes(
      6,
      f
    );
  }
};


/**
 * optional uint64 attr_id = 1;
 * @return {number}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getAttrId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setAttrId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string interface_name = 2;
 * @return {string}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getInterfaceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setInterfaceName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bytes ipv4_addr = 3;
 * @return {!(string|Uint8Array)}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4Addr = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes ipv4_addr = 3;
 * This is a type-conversion wrapper around `getIpv4Addr()`
 * @return {string}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4Addr_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getIpv4Addr()));
};


/**
 * optional bytes ipv4_addr = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIpv4Addr()`
 * @return {!Uint8Array}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4Addr_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getIpv4Addr()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setIpv4Addr = function(value) {
  return jspb.Message.setProto3BytesField(this, 3, value);
};


/**
 * optional uint32 mask = 4;
 * @return {number}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getMask = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setMask = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional bytes ipv4_default_route = 5;
 * @return {!(string|Uint8Array)}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DefaultRoute = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * optional bytes ipv4_default_route = 5;
 * This is a type-conversion wrapper around `getIpv4DefaultRoute()`
 * @return {string}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DefaultRoute_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getIpv4DefaultRoute()));
};


/**
 * optional bytes ipv4_default_route = 5;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIpv4DefaultRoute()`
 * @return {!Uint8Array}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DefaultRoute_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getIpv4DefaultRoute()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setIpv4DefaultRoute = function(value) {
  return jspb.Message.setProto3BytesField(this, 5, value);
};


/**
 * repeated bytes ipv4_dns = 6;
 * @return {!(Array<!Uint8Array>|Array<string>)}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DnsList = function() {
  return /** @type {!(Array<!Uint8Array>|Array<string>)} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * repeated bytes ipv4_dns = 6;
 * This is a type-conversion wrapper around `getIpv4DnsList()`
 * @return {!Array<string>}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DnsList_asB64 = function() {
  return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(
      this.getIpv4DnsList()));
};


/**
 * repeated bytes ipv4_dns = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIpv4DnsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.getIpv4DnsList_asU8 = function() {
  return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(
      this.getIpv4DnsList()));
};


/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.setIpv4DnsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.addIpv4Dns = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.NetworkInterfaceDetails} returns this
 */
proto.normalgw.platform.NetworkInterfaceDetails.prototype.clearIpv4DnsList = function() {
  return this.setIpv4DnsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.normalgw.platform.ServiceStatusDetails.repeatedFields_ = [1,2,3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.platform.ServiceStatusDetails.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.platform.ServiceStatusDetails} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.ServiceStatusDetails.toObject = function(includeInstance, msg) {
  var f, obj = {
    nameList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    detailsList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    statusList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    statusTimeList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.platform.ServiceStatusDetails}
 */
proto.normalgw.platform.ServiceStatusDetails.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.platform.ServiceStatusDetails;
  return proto.normalgw.platform.ServiceStatusDetails.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.platform.ServiceStatusDetails} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.platform.ServiceStatusDetails}
 */
proto.normalgw.platform.ServiceStatusDetails.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addDetails(value);
      break;
    case 3:
      var value = /** @type {!Array<!proto.normalgw.platform.ServiceStatus>} */ (reader.readPackedEnum());
      msg.setStatusList(value);
      break;
    case 4:
      var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
      msg.setStatusTimeList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.platform.ServiceStatusDetails.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.platform.ServiceStatusDetails} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.ServiceStatusDetails.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNameList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getDetailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getStatusList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
  f = message.getStatusTimeList();
  if (f.length > 0) {
    writer.writePackedUint64(
      4,
      f
    );
  }
};


/**
 * repeated string name = 1;
 * @return {!Array<string>}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.getNameList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.setNameList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.addName = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.clearNameList = function() {
  return this.setNameList([]);
};


/**
 * repeated string details = 2;
 * @return {!Array<string>}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.getDetailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.setDetailsList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.addDetails = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.clearDetailsList = function() {
  return this.setDetailsList([]);
};


/**
 * repeated ServiceStatus status = 3;
 * @return {!Array<!proto.normalgw.platform.ServiceStatus>}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.getStatusList = function() {
  return /** @type {!Array<!proto.normalgw.platform.ServiceStatus>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.normalgw.platform.ServiceStatus>} value
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.setStatusList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.normalgw.platform.ServiceStatus} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.addStatus = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.clearStatusList = function() {
  return this.setStatusList([]);
};


/**
 * repeated uint64 status_time = 4;
 * @return {!Array<number>}
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.getStatusTimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.setStatusTimeList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.addStatusTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.normalgw.platform.ServiceStatusDetails} returns this
 */
proto.normalgw.platform.ServiceStatusDetails.prototype.clearStatusTimeList = function() {
  return this.setStatusTimeList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.platform.GetSystemInformationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.platform.GetSystemInformationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.platform.GetSystemInformationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.GetSystemInformationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.platform.GetSystemInformationRequest}
 */
proto.normalgw.platform.GetSystemInformationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.platform.GetSystemInformationRequest;
  return proto.normalgw.platform.GetSystemInformationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.platform.GetSystemInformationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.platform.GetSystemInformationRequest}
 */
proto.normalgw.platform.GetSystemInformationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.platform.GetSystemInformationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.platform.GetSystemInformationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.platform.GetSystemInformationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.GetSystemInformationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.normalgw.platform.GetSystemInformationReply.prototype.toObject = function(opt_includeInstance) {
  return proto.normalgw.platform.GetSystemInformationReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.normalgw.platform.GetSystemInformationReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.GetSystemInformationReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    siteName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.normalgw.platform.GetSystemInformationReply}
 */
proto.normalgw.platform.GetSystemInformationReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.normalgw.platform.GetSystemInformationReply;
  return proto.normalgw.platform.GetSystemInformationReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.normalgw.platform.GetSystemInformationReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.normalgw.platform.GetSystemInformationReply}
 */
proto.normalgw.platform.GetSystemInformationReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSiteName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.normalgw.platform.GetSystemInformationReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.normalgw.platform.GetSystemInformationReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.normalgw.platform.GetSystemInformationReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.normalgw.platform.GetSystemInformationReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSiteName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string site_name = 1;
 * @return {string}
 */
proto.normalgw.platform.GetSystemInformationReply.prototype.getSiteName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.normalgw.platform.GetSystemInformationReply} returns this
 */
proto.normalgw.platform.GetSystemInformationReply.prototype.setSiteName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.normalgw.platform.ServiceStatus = {
  DOWN: 0,
  UP: 1,
  UNKNOWN: 3
};

goog.object.extend(exports, proto.normalgw.platform);
