{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Points",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT p.count + e.count as \"Total\", p.count as \"Trended\", e.count as \"Equips\", m.count as \"Labeled\"\nFROM (SELECT COUNT(*)\n      FROM metadata) as p\n         CROSS JOIN (SELECT COUNT(*)\n                     FROM model_metadata\n                     WHERE class IS NOT NUlL) as m\n         CROSS JOIN (SELECT COUNT(*)\n                     FROM equips) as e"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT device_vendor_name as metric, count(*) as value  FROM bacnet_metadata\nWHERE object_type = 'OBJECT_DEVICE'\nGROUP BY device_vendor_name\n"
    }
   ]
  },
  { "title": "Panel Title", "type": "dashlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 } },
  { "title": "Equipment Schedule", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Equipment Types",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT et.name as \"Equipment Type\", e.equips_count as \"Count\", p.points_count as \"Points\", s.\"0 Classes\", s.\"1-5 Classes\", s.\"6+ Classes\"\nFROM equipment_types et\n         JOIN (SELECT equip_type, count(*) as points_count\n               FROM model_metadata\n               GROUP BY equip_type) p ON et.id = p.equip_type\n         JOIN (SELECT equiptypeid, count(*) as equips_count\n               FROM equips\n               GROUP BY equiptypeid) e ON et.id = e.equiptypeid\n         JOIN (SELECT equiptypeid,\n                      count(*) filter ( where count = 0 )            as \"0 Classes\",\n                      count(*) filter ( where count between 1 and 5) AS \"1-5 Classes\",\n                      count(*) filter ( where count >= 6 )           as \"6+ Classes\"\n               FROM equips_points_stat\n               GROUP BY equiptypeid) as s ON et.id = s.equiptypeid\n"
    }
   ]
  },
  {
   "title": "Point Classes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT class, count(*) points FROM model_metadata\n                       WHERE class IS NOT null\n                       GROUP BY class\nORDER BY points DESC"
    }
   ]
  }
 ]
}