version: "2.1"

volumes:
  redis-db:
  nf-var:

services:
  redis:
    image: normalframework.azurecr.io/normalframework/redis:3.10.0-0
    ports:
      - "6379:6379"
    volumes:
      - "redis-db:/data"

  nf:
    image: normalframework.azurecr.io/normalframework/nf-full:3.10.0-0
    network_mode: host
    privileged: true
    environment:
      - PORT=80
    #   uncomment these to enable support for the bluetooth configuration app
    #   - NWCONFIG_ENABLED=true
    #   this variable sets how long after device boot the BLE configuration service is available.  For security, it's best not to leave it active forever.
    #   - NWCONFIG_BLE_TIMEOUT=900s
    #   - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    # labels:
    #   io.balena.features.dbus: '1'
    depends_on:
      - redis
    volumes:
      - "nf-var:/var/nf"

